package io.github.seraphina.myledger.ui.theme

import androidx.compose.ui.graphics.Color

val TealPrimaryLight = Color(0xFF00696D)
val TealOnPrimaryLight = Color(0xFFFFFFFF)
val TealContainerLight = Color(0xFF97F0F5)
val TealOnContainerLight = Color(0xFF002022)
val SlateSecondaryLight = Color(0xFF4A6365)
val SlateOnSecondaryLight = Color(0xFFFFFFFF)
val SlateContainerLight = Color(0xFFCDE7E9)
val SlateOnContainerLight = Color(0xFF051F21)
val IndigoTertiaryLight = Color(0xFF4B607C)
val IndigoOnTertiaryLight = Color(0xFFFFFFFF)
val IndigoContainerLight = Color(0xFFD3E4FF)
val IndigoOnContainerLight = Color(0xFF041C35)
val ErrorLight = Color(0xFFBA1A1A)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFFAFDFC)
val OnBackgroundLight = Color(0xFF191C1D)
val SurfaceVariantLight = Color(0xFFDBE4E6)
val OnSurfaceVariantLight = Color(0xFF3F484A)
val OutlineLight = Color(0xFF6F797A)

val TealPrimaryDark = Color(0xFF4FD8E0)
val TealOnPrimaryDark = Color(0xFF003739)
val TealContainerDark = Color(0xFF004F53)
val TealOnContainerDark = Color(0xFF97F0F5)
val SlateSecondaryDark = Color(0xFFB1CBD0)
val SlateOnSecondaryDark = Color(0xFF1B3437)
val SlateContainerDark = Color(0xFF324B4E)
val SlateOnContainerDark = Color(0xFFCDE7E9)
val IndigoTertiaryDark = Color(0xFFB3C8E8)
val IndigoOnTertiaryDark = Color(0xFF1D314B)
val IndigoContainerDark = Color(0xFF344863)
val IndigoOnContainerDark = Color(0xFFD3E4FF)
val ErrorDark = Color(0xFFFFB4AB)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF191C1D)
val OnBackgroundDark = Color(0xFFE1E3E3)
val SurfaceVariantDark = Color(0xFF3F484A)
val OnSurfaceVariantDark = Color(0xFFBFC8CA)
val OutlineDark = Color(0xFF899294)

val IncomeGreenLight = Color(0xFF0E7C4A)
val IncomeGreenDark = Color(0xFF6EDBA4)
val ExpenseRedLight = Color(0xFFB3261E)
val ExpenseRedDark = Color(0xFFFFB4AB)
